### PR TITLE
[WIP] Fix day on day view, move xsl files into own folder

### LINKED ISSUE #42: Wrong date and events for day view

### PR DESCRIPTION
**Pull request by riesinger**
This fixes #42

### CODE REVIEW

**Comment by christopherpielka** [comment]
Date still seems to be one day in the future. E.g. Date shows 28.06.2018 but the event which is shown is on 27.06.2018.

**Comment by christopherpielka** [comment]
Seems to be fixed with #64

**Comment by mheidinger** [comment]
@riesinger How does #64 affect this merge? Is it still up to date or is everything already implemented except for moving the xsl files?

**Comment by mheidinger** [comment]
Closed due to #64

**Pull request closed without merging**
